name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches:
      - main  # altere se quiser outro branch

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Instalar dependências e build do frontend
        working-directory: frontend
        run: |
          npm install
          npm run build

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20

      - name: Instalar dependências Go
        run: go mod download

      - name: Copiar frontend para backend/web
        run: |
          rm -rf web
          mkdir -p web
          cp -r frontend/dist/* web/

      - name: Build do binário Go
        run: |
          GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o app

      - name: Criar pacote ZIP para deploy
        run: zip -r deploy.zip app Procfile web/

      - name: Deploy para Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: smart-retention
          environment_name: smart-retention-env
          region: us-east-1
          version_label: v-${{ github.run_number }}
          deployment_package: deploy.zip
