name: Deploy Backend to AWS (ECS + ECR)

on:
  push:
    paths:
      - 'apps/backend/**'
    branches:
      - main

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, Tag, Push Docker image
        run: |
          cd apps/backend
          docker build -t ${{ secrets.ECR_REPOSITORY_URI }}:latest .
          docker push ${{ secrets.ECR_REPOSITORY_URI }}:latest

      - name: Force ECS service update
        run: |
          aws ecs update-service \
            --cluster smart-retention-ecs-cluster \
            --service smart-retention-service \
            --force-new-deployment
